### ISSUE TITLE
Distinguish between left and right Cmd buttons for hotkeys

### ISSUE THREAD

**Issue by aronasorman** [sdegutis/mjolnir#101]
Title says it all. It would be nice if I can bind my mod key to be only the right Cmd key.

**Comment by sdegutis** [comment]
Hmm good idea. I think this is possible. Will look into it.

**Comment by sdegutis** [comment]
@aronasorman :cake:

**Comment by sdegutis** [comment]
Closing in favor of #206 which is more generic.
