### ISSUE TITLE
Is there a way to notify hydra when a new window is created?

### ISSUE THREAD

**Issue by aronasorman** [sdegutis/mjolnir#104]
I browsed over the documentation and there seems to be no clean way of notifying the config script if a new window is launched. So if I launch a new firefox window the only way to automatically tile it would be to poll every X milliseconds and then act accordingly.

**Comment by sdegutis** [comment]
You're right, polling is not ideal for this. There is an issue in the 1.1 milestone for creating events, and "window-opened" is one of them. So expect this feature soon!

**Comment by sdegutis** [comment]
The issue is #72 by the way.
