### ISSUE TITLE
Each time you kill hydra it should spawn two more processes

### ISSUE THREAD

**Issue by paytonrules** [sdegutis/mjolnir#105]
![pasted_image_7_3_14__10_25_am](https://cloud.githubusercontent.com/assets/21752/3471849/48b6692a-02c6-11e4-9265-cb6236c6eb41.png)

**Comment by sdegutis** [comment]
Closed as a duplicate.

**Comment by sdegutis** [comment]
(@paytonrules get it? duplicate? lol)

**Comment by sdegutis** [comment]
:cake:
