### ISSUE TITLE
Dynamic reloads

### ISSUE THREAD

**Issue by EricR** [sdegutis/mjolnir#106]
I didn't see this documented in the API, but apologies if this already exits somewhere!

I think it would be really useful to be able to dynamically load lua files other than init. I'm currently using this to reload all of my custom files alongside init when hydra.reload gets called:

``` lua
function rerequire(module)
  package.loaded[module] = nil
  return require(module)
end
```

**Comment by sdegutis** [comment]
@EricR I think `hydra.douserfile` is what you're looking for. Either type `doc.hydra.douserfile` in the REPL, or check out the online docs here: http://sdegutis.github.io/hydra/hydra.html#douserfile -- does this look like what you're looking for?

**Comment by sdegutis** [comment]
I'll update the documentation overview page (index.html) to explain this in better detail.
