### ISSUE TITLE
Doc: add an index page

### ISSUE THREAD

**Issue by muescha** [sdegutis/mjolnir#108]
I miss a index page. 

I see comand hydra.douser file but not found the dofile command in doc

**Comment by sdegutis** [comment]
@muescha it is part of Lua's API. See the Lua API link on the readme page.

**Comment by sdegutis** [comment]
@muescha Does #109 meet your needs for this issue, so that I can close it?

**Comment by sdegutis** [comment]
@muescha I think we're saying the same thing

**Comment by sdegutis** [comment]
@muescha I am splitting this out into two issues: #136 and #109.
