### ISSUE TITLE
Link between commands in docs

### ISSUE THREAD

**Issue by muescha** [sdegutis/mjolnir#110]
It should do autolink to a command if it is a know command

I see comand hydra.douser file but not found the dofile command in doc

**Comment by sdegutis** [comment]
@muescha oh yeah totally, i would love a "see also" feature for docs; but a clickable-keyword feature would be much harder, I don't even know how I would implement it.. ideas?

**Comment by sdegutis** [comment]
@muescha the web docs use markdown right now, but they come from the same source as the in-app docs (via repl); and I don't want to clutter the in-app docs with ugly markdown links

**Comment by sdegutis** [comment]
@muescha I like that idea.
