### ISSUE TITLE
Access and modify window/document contents

### ISSUE THREAD

**Issue by chrisdevereux** [sdegutis/mjolnir#111]
Have you considered adding Lua calls for accessing and modifying window contents, selections, etc?

OS X has a rich collection of APIs supported by basically every Cocoa app via Scripting Bridge and AXAccessibility. Being able to script this stuff easily from within Lua + attach keybindings would be awesome.

**Comment by sdegutis** [comment]
@chrisdevereux thanks, added to 1.1 milestone

**Comment by sdegutis** [comment]
This is definitely possible. I'd love to expose this API under maybe an `accessibility` module. It would actually be pretty trivial to do a 1:1 mapping, if I'm not mistaken.
