### ISSUE TITLE
Add spaces module

### ISSUE THREAD

**Issue by philsnow** [sdegutis/mjolnir#116]
It would be lovely to be able to programmatically push windows around between spaces / workspaces / whatever os x calls them this year.

**Comment by sdegutis** [comment]
This may be helpful in adding this feature: http://ianyh.com/blog/2013/09/24/identifying-spaces-in-mac-os-x/

**Comment by sdegutis** [comment]
This will also be helpful: http://ianyh.com/blog/2013/06/05/accessibility/

If memory serves, the trick to "switching spaces" is basically just faking the hotkeys that switch spaces.

**Comment by sdegutis** [comment]
We should just use private APIs, like osxmonad does in this commit: https://github.com/xmonad/osxmonad/commit/66b1f7431d60287d4449dec2e2251a4ea3a96ff6

**Comment by sdegutis** [comment]
Found a way to get notified when the current space changes. Doing it is trivial, but not sure what the API should look like.

**Comment by sdegutis** [comment]
This [commit from osxmonad](https://github.com/xmonad/osxmonad/commit/66b1f7431d60287d4449dec2e2251a4ea3a96ff6) may be instructional.

**Comment by sdegutis** [comment]
Using the following code derived from @puffnfresh's xmonad and @fjolnir's xnomad projects, I can switch spaces. But it doesn't work with Mission Control (in 10.9)... swiping four fingers upwards will reset me back to the space I switched from.

``` objc
uint64_t from, to;

// ... use CGSCopySpaces() with kCGSSpaceCurrent and kCGSSpaceAll to get `from` and `to`
// they're small-ish numbers (mine were 3 and 22, respectively)

CGSHideSpaces(_CGSDefaultConnection(), (__bridge_retained CFArrayRef)@[@from]);
CGSShowSpaces(_CGSDefaultConnection(), (__bridge_retained CFArrayRef)@[@to]);
CGSManagedDisplaySetCurrentSpace(_CGSDefaultConnection(), kCGSPackagesMainDisplayIdentifier, to);
```

**Comment by sdegutis** [comment]
Just pushed sdegutis/hydra@fb4ef150f827a5a78fa0b9ba7f75ac4e43d54860, which adds experimental support!

Nearly a second before I pushed it, @puffnfresh suggested [in this comment](https://github.com/xmonad/osxmonad/commit/66b1f7431d60287d4449dec2e2251a4ea3a96ff6#commitcomment-7105006) that this API is broken on Mavericks. I don't yet know if there's a replacement.
