### ISSUE TITLE
Need to quit and restart after updating an external class

### ISSUE THREAD

**Issue by thyselius** [sdegutis/mjolnir#118]
Thanks for a WONDERFUL tool!

I'm editing a custom class (forked from the grid class) and when I save the file it I can tell that Hydra is reloaded (I get the alert). 

However my new changes are not available, it's the old class file. If I then manually quit Hydra and then start it again, it's the new class.

**Comment by sdegutis** [comment]
@thyselius That's because `require` caches the file. If you're actively working on it, use `hydra.douserfile` instead. There's an issue to clarify this in the docs; see #107.
