### ISSUE TITLE
Question: How do I list/find the application name for apps?

### ISSUE THREAD

**Issue by thyselius** [sdegutis/mjolnir#121]
Hi!

Thanks again for a great tool. One quick questions.

I want to focus an app only if it's running. I tried application.runningapplications() but I couldn't get it to work. Can you please point me in the right direction here?

**Comment by sdegutis** [comment]
@thyselius look for the app in `application.runningapplications()` by comparing the `app:title()`, and if you find the one you're looking for, run `app:activate()`. See http://sdegutis.github.io/hydra/application.html for more info.
