### ISSUE TITLE
Install via homebrew / cask

### ISSUE THREAD

**Issue by joshka** [sdegutis/mjolnir#122]
https://news.ycombinator.com/item?id=7985018

[-] 1 point by joshka 10 hours ago | link | parent | on: Hydra: A lightweight OS X window manager with a po...

Cool tool. Would be a good idea to get it on homebrew for one liner install. I noticed when checking whether it was on homebrew that there's another piece of software already by that name that could be worth avoiding (despite being an almost perfect name for what this does).
reply

[-] sdegutis 5 hours ago | link

I think GUI apps only go in cask[1](http://caskroom.io/) not homebrew. But yeah, totally a good idea to put it in there. Thanks! Can you file an issue for this in Hydra?

**Comment by sdegutis** [comment]
Someone did this 2 hours before I filed #117 :) see the readme for how to do it :+1:
