### ISSUE TITLE
What are the binding strings for the arrow keys?

### ISSUE THREAD

**Issue by autodidacticon** [sdegutis/mjolnir#123]
eg. **hotkey.bind({"ctrl","_arrow_left_", my_function()....**

**Comment by sdegutis** [comment]
@autodidacticon Good question! This really should be clarified in the docs. For anything you can type with an obvious single-character, that character is what you put here. For everything else, here is [the definitive list](https://github.com/sdegutis/hydra/blob/master/Hydra/hotkey_translator.m#L64-L120). But this really ought to be said in the docs for the `hotkey` module.
