### ISSUE TITLE
installation package not accessible

### ISSUE THREAD

**Issue by zinking** [sdegutis/mjolnir#128]
I had issue opening  https://s3.amazonaws.com/github-cloud/releases/...  I assuming the installation won't be that big, is it possible to directly attach it to github folder ?

**Comment by sdegutis** [comment]
@zinking are you talking about https://github.com/sdegutis/hydra/releases/download/v1.0.b6/Hydra-1.0.0.b6.app.tar.gz ?

**Comment by sdegutis** [comment]
@zinking Okay, thanks.
