### ISSUE TITLE
REPL Linebreak not working correctly

### ISSUE THREAD

**Issue by wsterzik** [sdegutis/mjolnir#129]
After linebreak characters entered are not displayed
![activeanchoredincatern](https://cloud.githubusercontent.com/assets/4449714/3479452/3171eece-0352-11e4-9fa4-885b215ad5f8.gif)

**Comment by sdegutis** [comment]
@wsterzik lol that is a funny bug :)

**Comment by sdegutis** [comment]
@asmagill textgrids are funny little things.. the real solution here is for `repl.lua` to use them right.. and it wouldn't hurt if I documented them at all, either

**Comment by sdegutis** [comment]
The REPL was written in a hurry and it shows; one of the tasks in the 2.0 milestone is to make it much higher quality.

**Comment by sdegutis** [comment]
Superseded by #240.
