### ISSUE TITLE
application.runningapps vs. runningapplications

### ISSUE THREAD

**Issue by Habbie** [sdegutis/mjolnir#132]
```
    {"runningapps", application_runningapplications},

    "application", "runningapplications", "application.runningapplications() -> app[]",
```

Inconsistency means docs (`runningapplications`) don't match reality (`runningapps`). Not sure which name is best, so did not make a pull.

**Comment by sdegutis** [comment]
@Habbie It should be called `application.runningapplications`, thanks for the catch.
