### ISSUE TITLE
Easy navigation/focus based on initial character of the application

### ISSUE THREAD

**Issue by cksachdev** [sdegutis/mjolnir#134]
Another alternative to focusing on the windows except using window.focusedwindow():focuswindow_xxxx().
### Feature details:

```
Caps Lock + T -> Focus on Terminal (if open)
Caps Lock + G -> Focus on Google Chrome (if open)
Caps Lock + S -> Sublime Text 3
Caps Lock + S -> Skype (Repeating the same key press again, should move to the next application matching name)
Caps Lock + S -> Safari
```
#### Adding to it, it will be great if mouse cursor moves to the center of the window, which is supposed to be focused.

I achieved this in Slate to some extent using **PC Keyboard Hack**, where it changes my Caps Lock key to F19 key and then using this combination of keys to easily focus. Would be great if it doesnt require these third party application and enables the so called **Hyper key** and changes it to one single key i.e. Capslock.

**Comment by sdegutis** [comment]
@cksachdev everything except your last paragraph is already possible via the current Hydra API, but will not be implemented as part of hydra-core, and should instead be implemented as a third party extension and put in the wiki; the last paragraph will be possible when #9 is finished.

**Comment by rileyjshaw** [comment]
@cksachdev did you ever figure this out?
