### ISSUE TITLE
Windows do not bear an identifier.

### ISSUE THREAD

**Issue by nkp** [sdegutis/mjolnir#137]
This is best demonstrated in the REPL, running:

```
window.focusedwindow()
```

twice does not return the same object:

```
> window.focusedwindow()
table: 0x60800046d780

> window.focusedwindow()
table: 0x60800046d780
```

This would not be a problem if windows carried a unique id that was consisted across calls to focusedwindow, allwindows, etc. The only way to currently do this with the existing API is to use a combination of the application bundleid and the title; which is almost useless as many windows can share title and application and the title can change (Web browser).

**Comment by sdegutis** [comment]
@nkp they can be compared via `win1 == win2`, does that suit your needs?

**Comment by sdegutis** [comment]
@nkp Ah good point.

**Comment by sdegutis** [comment]
There already is an identifier, I'll just make it public.
