### ISSUE TITLE
Add modal hotkeys module

### ISSUE THREAD

**Issue by ihodes** [sdegutis/mjolnir#138]
In e.g. Moom (or many other apps) you can activate a mode with a key combination. Once in the mode, keyboard commands or just letters are bound to function (e.g. F could make the current window fullscreen). This prevents you from need a separate key-chord for each function. Would something like this be possible and desirable for Hydra?

**Comment by sdegutis** [comment]
@ihodes someone has implemented this using the current API: https://gist.github.com/myeyesareblind/e3f1465ac7df875ea3d9 :)

**Comment by sdegutis** [comment]
I agree this should be in the official Hydra API. It is asked for quite enough.

**Comment by sdegutis** [comment]
Closing this in favor of issue #146 which is a pull request too.
