### ISSUE TITLE
Add ext.hotkey for display table of hotkeys and their descriptions

### ISSUE THREAD

**Issue by muescha** [sdegutis/mjolnir#140]
# what

i would like have my own bindings also documented in some way
- for use in repl
- to have a list of all my active bindings (something like shortcat )
# where

at bind command

```
hotkey.bind({"cmd", "ctrl", "alt"}, "L", movewindow_rightside, 
"documentation for this hotkey")
```

or if i like to tweak the order, then it is first sorted by "my.oder.key" and then by default sort:

```
hotkey.bind({"cmd", "ctrl", "alt"}, "L", movewindow_rightside, 
{"my.order.key" => "documentation for this hotkey"})
```
# display

maybe as a command (pseudocode) 

```
mydoc = doc.custom.generate #-> generates String to display in my custom dialog
```

or and api function to display all active bindings to the user (as a cheetsheet):

```
doc.custom.show_help_screen()
```

**Comment by sdegutis** [comment]
@muescha You can wrap `hotkey.bind` in your own custom function which uses the mods and key and also takes an extra docstring param and uses these to build up a table of your own hotkeys. Then you could add a function that displays these in a textgrid. I'm not sure if this is universally useful enough to merit being built-into Hydra, but it at least does sound like it would be a useful `ext` module.
