### ISSUE TITLE
close() method on window?

### ISSUE THREAD

**Issue by MattSPalmer** [sdegutis/mjolnir#141]
Great software, enjoying it so far. Only thing that jumps out at me is the lack of a close() method on window. Any chance it's coming soon?

**Comment by sdegutis** [comment]
Oh wow, this is a really ugly solution, [literally pressing the button for the user](http://stackoverflow.com/questions/8898430/close-all-windows-of-another-app-using-accessibility-api). Hopefully I can find a better one using `AXUIElementPerformAction`.

**Comment by sdegutis** [comment]
Nope, looks like `AXActionConstants.h` is super high-level; guess we'll do it the ugly way.
