### ISSUE TITLE
Config Option to Remove Drop Shadow

### ISSUE THREAD

**Issue by creese** [sdegutis/mjolnir#142]
I'm using Hydra as tiling WM. Since my windows never overlap, I like to turn off drop shadows. It would be nice if I could do this from my config so I don't need a separate tool.

Here is an example of what I mean.
https://github.com/puffnfresh/toggle-osx-shadows

**Comment by sdegutis** [comment]
It's really really simple to do. The question is, should this be part of Hydra? It can't be done in pure Lua, so it can't be a third party extension, _unless_ it's compiled as a .so file; that's the direction I'm leaning towards.

**Comment by sdegutis** [comment]
Added in 1.1
