### ISSUE TITLE
Tab completion in REPL

### ISSUE THREAD

**Issue by af** [sdegutis/mjolnir#143]
I don't know how feasible they are to implement, but here are two things I'd love to see in the REPL:

1) Add tab completion, eg typing `windo<tab>` completes to `window`
2) Support up/down arrow keys to go back/forward in the REPL history.

Loving hydra, I was a zephyros fan and this seems even better!

**Comment by sdegutis** [comment]
1) for global modules and table keys this should be totally possible
2) good point; created #114 for that feature
3) appreciated <3

**Comment by sdegutis** [comment]
Superseded by #240.
