### ISSUE TITLE
"Open sample config" does nothing

### ISSUE THREAD

**Issue by raine** [sdegutis/mjolnir#145]
Nothing happens when I select "Open sample config" in the menu.

```
https://github.com/sdegutis/hydra/releases/download/v1.0.b6/Hydra-1.0.0.b6.app.tar.gz
```

**Comment by sdegutis** [comment]
@raine fixed in beta 7

**Comment by sdegutis** [comment]
@wengzilla Thanks for the report. Trying it now on Hydra 0.13

**Comment by sdegutis** [comment]
@wengzilla It works for me in Hydra 0.13 when I downloaded it from the site. How did you install it?
