### ISSUE TITLE
inaccurate name/comments in sample config?

### ISSUE THREAD

**Issue by bmatsuo** [sdegutis/mjolnir#147]
I just installed v1.0.b7 with cask and copied the sample config to init.lua.

I'm confused by these lines

https://github.com/sdegutis/hydra/blob/e37073dacf2a89aa7776259150ac0779e9105402/Hydra/sample_config.lua#L33-L40

Pressing cmd+ctrl+alt+R moved the window to the left half of the screen despite the function name, comments, and key press suggesting it should move to the right half. Uncommenting the suggested line moved the window to the right half of the screen.

Am I somehow experiencing unexpected behavior?

**Comment by sdegutis** [comment]
@bmatsuo lol no you're right I wrote the comments wrong by accident, oops. le sigh.

**Comment by sdegutis** [comment]
:cake:
