### ISSUE TITLE
Add API for system volume controls

### ISSUE THREAD

**Issue by af** [sdegutis/mjolnir#149]
It would be great to be able to control the system audio volume (mute/volume+/volume-) from Hydra. You [can change the volume through AppleScript](http://blog.coolaj86.com/articles/how-to-control-os-x-system-volume-with-applescript/), but the API is gross and you don't get OS X's nice overlay UI when you make those calls.

There must be some (probably Objective-C) API to access the system volume/mute controls, because the [Spark](http://www.shadowlab.org/softwares/spark.php) app lets you bind arbitrary keyboard shortcuts for them. Maybe [this discussion](http://stackoverflow.com/questions/17715111/change-os-x-system-volume-programmatically) points to a solution?

**Comment by sdegutis** [comment]
@BrianGilbert please file a new issue for that thanks :)

**Comment by sdegutis** [comment]
@jhgg great! how about these changes?

``` lua
audio.defaultoutputdevice() -> audio -- an "audio" object
audio.alloutputdevices() -> audio[] -- array of "audio" objects
audio:setvolume(number) -> boolean -- sets the volume of the device.
audio:volume() -> number -- gets the volume of the device. 
audio:name() -> string -- gets the device name
```

**Comment by sdegutis** [comment]
I know an "audio" feels a bit weird as an instance name, but it makes the module self-consistent; what do you think of my proposed changes?

**Comment by sdegutis** [comment]
@af Seems if that's as simple as `audio:setvolume(audio:volume() + 6.25)` then I'm conflicted on including it.. but leaning towards agreeing that it should be included.

**Comment by sdegutis** [comment]
But I'd name them `audio:incvolume(n)` and `audio:decvolume(n)`

**Comment by sdegutis** [comment]
My only reason for preferring `volume:{inc,dec}volume()` is that the method name reads like a sentence, such as in `window:setframe` etc.

**Comment by sdegutis** [comment]
I can't help but wonder if the functions shouldn't be sorted alphabetically in the docs. I'd prefer them to be defined in the app in the same order they should appear in the docs. The main problem with this is when it comes to modules half defined in Lua and half in C. But obviously there are other problems with coupling function definitions to documentation order that make me uneasy too.

**Comment by sdegutis** [comment]
@jhgg +1

**Comment by sdegutis** [comment]
This was completed by #246. Woo!
