### ISSUE TITLE
Add selection feature to REPL (for copying text)

### ISSUE THREAD

**Issue by BrianGilbert** [sdegutis/mjolnir#150]

**Comment by sdegutis** [comment]
@BrianGilbert sounds like a super useful feature; you okay with doing it emacs-style until #35 is finished?

**Comment by sdegutis** [comment]
Yeah except simpler:
- `C-space` to set or reset the mark to where the point is
- Move anywhere to set the point
- `C-w` to cut from mark to point
- `M-w` to copy from mark to point
- `C-y` to paste at point

**Comment by sdegutis** [comment]
@BrianGilbert that's not counter to Hydra's principles at all; in fact #35 is set for the 1.1 milestone :)

**Comment by sdegutis** [comment]
@muescha Heh, I must have been using Emacs for quite a while now, because that thought never crossed my mind. Anyway, I do prefer the Emacs way.

**Comment by sdegutis** [comment]
Superseded by #240.
