### ISSUE TITLE
Request: Ability to display brief overlay of grid when it's size get's changed

### ISSUE THREAD

**Issue by BrianGilbert** [sdegutis/mjolnir#152]
Probably also will want to be able to just show current grid somehow.

@sdegutis said
realityloop: hmm.... i bet a textgrid with a semitransparent background could work for that... that's probably possible in general, but not in the current API which assumes a 6-digit hex code for colors; it would need 2 more digits for alpha

**Comment by sdegutis** [comment]
Pushing this to 1.1
