### ISSUE TITLE
Add function in window to see if it's being dragged by the mouse.

### ISSUE THREAD

**Issue by TrainerGuy22** [sdegutis/mjolnir#153]
Something like `window:dragged()` or something? Not sure how possible it, it /might/ be a flag in NSWindow or something?

The use for it would be for mouse manipulation with windows, things like visual window snap and the like.

EDIT: It seems possible via the accessibility API, or with a Cocoa AppDelegate (from a quick Google).

**Comment by sdegutis** [comment]
Dunno if it's possible. Will investigate.

**Comment by sdegutis** [comment]
possibly; noticed a mouse-dragged event; not sure if there's one for windows specifically

**Comment by sdegutis** [comment]
Looks like it can't.

**Comment by sdegutis** [comment]
Closing as impossible.
