### ISSUE TITLE
window:frame() and screen:visibleframe() return conflicting y coordinates

### ISSUE THREAD

**Issue by jhgg** [sdegutis/mjolnir#163]
I have a hex monitor setup. Where each monitor is setup as follows 

```
| 4 | 5 | 6 |
| 1 | 2 | 3 |
```

When a windows is maximized in the top windows, the magnitude of the y value of the rect is wrong!

In this example, on monitor 5 you can see what happens the REPL:

![screenshot_7_5_14__10_48_pm](https://cloud.githubusercontent.com/assets/5489149/3487955/27b5b82c-04b8-11e4-89e9-5ccfae3a2a39.png)

**Comment by sdegutis** [comment]
@jhgg Not sure if it's related or not, but in Hydra's coordinate grid, {0,0} always refers to the top-left corner of the screen which has the menu bar's focus.

**Comment by sdegutis** [comment]
@jhgg Hmm. I'm pretty confused by this. Will have to give it some serious thought later. For the record, I wrote the `ext.grid` module years ago (originally in Objective-C) which is when I did all the thinking and calculating about it; I haven't actually looked at any of the raw numbers involved since then.

**Comment by sdegutis** [comment]
@jhgg Does `screen:frame_without_dock_or_menu()` return a more convenient value?

**Comment by sdegutis** [comment]
@jhgg Now that I think about it, I'm pretty sure the reason I wrote `screen:frame_without_dock_or_menu()` and `screen:frame_including_dock_and_menu()` was to normalize `screen:frame()` and `screen:visibleframe()` for the same reason you opened this issue. In this case, using those longer methods should get you the values you're looking for, and I should make `screen:frame()` and `screen:visibleframe()` private. Can you confirm?

**Comment by sdegutis** [comment]
@jhgg Thanks :)

**Comment by sdegutis** [comment]
@jhgg Any news?

**Comment by sdegutis** [comment]
Closing this as I'm 99% sure it's been solved by using the aforementioned longer `screen` methods. If anyone finds otherwise feel free to reopen it.
