### ISSUE TITLE
application:activate() doesn't seem to immediately focus the app window sometimes

### ISSUE THREAD

**Issue by fent** [sdegutis/mjolnir#165]
It seems to happen when an app has been idle for a while. It doesn't display the last active window from that app to the front until I press another key on my keyboard, or a few seconds pass.

One workaround I've found is to do

``` lua
app:activate()
app:allwindows()[1]:focus()
```

Which is a BIG difference, and will switch to the window immediately.

`application:allwindows()` returns windows in the order of last focused, so this works for this case. But I feel like `application:activate()` alone should already do this.

**Comment by sdegutis** [comment]
This is strange. In the past, `app:activate()` used to be private, only used within `window:focus()` but I decided to split it out just in case it was useful. I suppose this means it's not actually all that useful.
