### ISSUE TITLE
Is it possible to open a webpage from a menu item?

### ISSUE THREAD

**Issue by BrianGilbert** [sdegutis/mjolnir#175]
I want to add a link to the hydra issues page :P

**Comment by sdegutis** [comment]
@BrianGilbert There's plenty of ways to do this, and none of them have to do with `fnutils` actually. I would personall just define a new function for clarity, but you could just write an inline function too:

``` lua
      {title = "Github Issues", fn = function() os.execute("open http://myurl") end},
```
