### ISSUE TITLE
hydra 1.0 beta 8 error in config

### ISSUE THREAD

**Issue by cksachdev** [sdegutis/mjolnir#176]
Updated from beta 6 to beta 8. Getting the error mentioned below:

Hydra Error

/Users/Sachdev/.hydra/grid.lua:13: attempt to index local 'win' (a nil value)
'''

**Comment by sdegutis** [comment]
@cksachdev You apparently passed a nil value to `ext.grid.get` at some point in your own config.

**Comment by sdegutis** [comment]
@moonsspoon do you get this error in beta 9?

**Comment by sdegutis** [comment]
Hmm...

**Comment by sdegutis** [comment]
@moonsspoon 

Using these:
- Hydra 1.0 Beta 9
- https://github.com/sdegutis/hydra/wiki/grid.lua/833b77276959b055f90c764c2b36ae6507d48b7e
- https://github.com/sdegutis/dotfiles/blob/osx/home/.hydra/init.lua

Taking these steps:
- Click somewhere on Google Chrome
- Hit Cmd-Opt-Shift L

And it focuses the window to Chrome's right. Thus I cannot reproduce what you're describing.
