### ISSUE TITLE
Add API for dock alerts

### ISSUE THREAD

**Issue by FND** [sdegutis/mjolnir#180]
While an API exists for text notifications, there doesn't seem to be a way to trigger a dock alert (i.e. make the respective application's icon bounce). That seems like a useful addition.

**Comment by sdegutis** [comment]
@FND Do you mean Hydra's dock icon, or the dock icon of another app (i.e. maybe Chrome or Finder)?

**Comment by sdegutis** [comment]
@FND Not sure if we can bounce another app's icon, but I know we can bounce our own.

**Comment by sdegutis** [comment]
But it probably wouldn't make sense unless you first had `hydra.putindock(true)`

**Comment by sdegutis** [comment]
As part of this, we should make a `dockicon` module, put these methods in there, and move `hydra.putindock -> dockicon.{show,hide}` and `hydra.indock -> dockicon.visible`.

**Comment by sdegutis** [comment]
I'm not sure how useful this feature really is. The only two real additions would be (1) making Hydra's dock icon bounce, and (2) show a custom string on it. The second one sounds maybe-sometimes useful, the first one doesn't.

![screen shot 2014-07-16 at 10 41 37 am](https://cloud.githubusercontent.com/assets/4399718/3601263/cf2d4cf6-0cff-11e4-87c1-600777a0b221.png)
