### ISSUE TITLE
Add screen:screento{north,south,east,west} methods

### ISSUE THREAD

**Issue by dljsjr** [sdegutis/mjolnir#182]
Currently, there are `screen:previous()` and `screen:next()` for cycling through screens, but it's even stated in the docs that these correspond to the "numbering" of the monitors which can be non-sequential.  It would be useful to have an API for querying a `screen` for other screens to the left and to the right of it (or for a crazy setup, maybe even above and below).  Coming from Slate, I have keybindings for moving app windows to adjacent monitors that I can't easily replace using Hydra (yet).

**Comment by sdegutis** [comment]
@dljsjr @jhgg This would be an almost-exact port of [the `windows_in_direction` Lua function](https://github.com/sdegutis/hydra/blob/9acc8589462489f7e75350077a80331ed0c063bf/Hydra/API/window.lua#L121-L196). I'm not sure if it's useful enough or difficult enough to merit being included in Hydra itself though. Maybe. Anyway it wouldn't be that hard to write, just very tedious to test.
