### ISSUE TITLE
Add API to simulate key presses

### ISSUE THREAD

**Issue by keith** [sdegutis/mjolnir#187]
I was looking for a way to have a hotkey trigger another arbitrary key combination. For example have a hotkey such as Shift+CMD+Enter bring an application to the foreground, if that application is already in the foreground it should hide it.

Obviously this is one use case but I think there are other interesting ones as well.

**Comment by sdegutis** [comment]
@Keithbsmiley For hotkeys you define in Hydra, you can just name its function and call it from two different places. So I'm interpreting what you're saying as, to simulate the pressing of any arbitrary keys from within Hydra. So if I want to paste, I just simulate Cmd-V via `hotkey.press({"cmd"}, "v")`.

**Comment by sdegutis** [comment]
There's a low-level API to this on the `next` branch:

``` lua
event.postkey(hotkey.keycodes.tab, {"cmd"}, "both")
```

Although I'm already not liking how there's key-related functionality split between the `hotkey` and `event` modules. Not sure if there's a clean resolution to that though.

**Comment by sdegutis** [comment]
@muescha the new API is:

``` lua
event.postkey({"cmd"}, "a")
-- optional third argument can be "pressrelease", "press", "release", or nil (defaults to "pressrelease")
```

This can easily be wrapped:

``` lua
for i = 1, #str do event.postkey({}, str:sub(i,i)) end
```

**Comment by sdegutis** [comment]
This is done in 1.1
