### ISSUE TITLE
Some kind of API for focus change hooking would be nice.

### ISSUE THREAD

**Issue by rburchell** [sdegutis/mjolnir#188]
I would like to call mouse.set() on focus change, so I can always rely on moving my cursor the minimum 'distance' so to speak. Kind of similar to what I've done in my hotkey bindings at https://github.com/rburchell/dotfiles/commit/a9c3f5572bb3f8eb6c85012961be9abd2f44133d for instance.

I've looked over the API documentation but I can't see any kind of callback provided for this.

**Comment by sdegutis** [comment]
@rburchell That's coming in the events feature (#72) for 1.1 milestone.
