### ISSUE TITLE
Hydra not working at all for me

### ISSUE THREAD

**Issue by blakeperdue** [sdegutis/mjolnir#191]
I've tried using sdegutis' config and the other config files listed in https://github.com/sdegutis/hydra/wiki/Other-people's-configs

Some kind of work, where one shortcut key will work but then it stops working. I can't get any of them to work at all. Is there an error log somewhere I can try looking at? Even the sample config file doesn't work.

I'm running Hydra-v1.0.b9 and I'm on 10.9.3

**Comment by sdegutis** [comment]
@blakeperdue Have you enabled accessibility for Hydra? If not, enable it and try again. If so, disable it, enable it, and try again.

**Comment by sdegutis** [comment]
@blakeperdue you sure it works then? that sound happens when you hit an invalid hotkey (i.e. it's probably not working)

**Comment by sdegutis** [comment]
@blakeperdue not every config has been updated for beta9 yet... fortunately the API has stabilized so that problem so go away in a few weeks

**Comment by sdegutis** [comment]
@blakeperdue Worked once you restarted? Sounds a lot like #193 to me. That seems rather urgent at this point.

**Comment by sdegutis** [comment]
Okay I'm counting it as another bug caused by #193. Sigh. I really need to fix that.
