### ISSUE TITLE
Hydra v1.0.b9 - "hotkey.lua:17: attempt to call field 'fn' (a nil value)"

### ISSUE THREAD

**Issue by neowulf** [sdegutis/mjolnir#194]
Using this [hydra config](https://github.com/neowulf33/personal/blob/7a4194a6cc55cd9862c51c9dd322769997cb9de6/mac_os_x/hydra/init.lua) :

I get the following error when pressing "CMD+ALT+OPT+L":

```
   Error: ...oom/hydra/1.0.b9/Hydra.app/Contents/Resources/hotkey.lua:17: attempt to call field 'fn' (a nil value)
```

I have tried to disable and re-enable the "System Preferences > Accessibility > Hydra" with no change.

**Comment by sdegutis** [comment]
@neowulf33 Make sure you're on beta 9

**Comment by sdegutis** [comment]
@neowulf33 Heh right, I should have seen it in your error message. Turns out you're calling `movewindow` and passing its return value (nil) as the callback function for the hotkey. Wrap it in `function() ... end` instead.
