### ISSUE TITLE
Add updates.upgrade()

### ISSUE THREAD

**Issue by BrianGilbert** [sdegutis/mjolnir#196]
perhaps http://sparkle-project.org/

Updating via cask:
-requires you to granty the app accessibility controls every time you update
-leaves old versions in /opt/homebrew-cask/Caskroom/hydra/

**Comment by sdegutis** [comment]
1. Updating via Sparkle would do the same thing.
2. Leaving old versions does kinda suck, but I'm not sure it's that bad in practice.

**Comment by sdegutis** [comment]
Also Sparkle is overkill for this. If we were gonna do something like that, we could do it ourselves. We have the code (and non-deprecated code at that!).

**Comment by sdegutis** [comment]
Agreed. Not a fan of that. Waiting on caskroom/homebrew-cask#4678. In the meantime, we may just roll our own solution. It's really not that hard, and I already did most of the work.

**Comment by sdegutis** [comment]
@rolandwalker thanks for the link, created #209 for it!

**Comment by sdegutis** [comment]
Pushing to 1.0 since the app icon isn't done anyway and there are no other 1.0 features left.

**Comment by sdegutis** [comment]
Tasks:
- [x] store public key in app
- [x] sign zip in release script with private key
- [ ] download zip into temporary directory
- [x] verify signature against public key
- [ ] replace running .app with downloaded .app and restart

We already have the code in the repo history for most of these. The only one I'm not 100% satisfied with is the last item on this list; my solution was quite janky. Years ago I wrote a very similar tool to what Sparkle used, which is a secondary executable stored in the Resources dir which can run in memory, use `wait` properly within C for the parent process to die, and replace the app bundle properly.

**Comment by sdegutis** [comment]
The commit 3109912d1baf141dd980ace54234e3297f535267 had a really good [updates.m](https://github.com/sdegutis/hydra/blob/3109912d1baf141dd980ace54234e3297f535267/Hydra/updates.m) file with the completed (and non-deprecated!) `transform_public_key` and `updater_verify_file` functions.

**Comment by sdegutis** [comment]
Just need to do something similar to [Autoupdate.m](https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/Autoupdate/Autoupdate.m) (but in our own way).

**Comment by sdegutis** [comment]
This feature depends on #171 so that we can download the file using Lua, mainly because I'm really sick of typing the same NSURLConnection code over and over.
