### ISSUE TITLE
window spacing

### ISSUE THREAD

**Issue by bjoernhaeuser** [sdegutis/mjolnir#199]
Hi,

thanks for making Hydra. Just started yesterday and it's totally amazing.

Is there a way to reduce the spacing between the toolbar and between the windows? Tried to find something in the docs, but was unable to find it :-(

![screen shot 2014-07-08 at 08 21 50](https://cloud.githubusercontent.com/assets/1449155/3505855/3a25502e-0668-11e4-9e3a-377218eb4f2c.png)

Thanks
Björn

**Comment by sdegutis** [comment]
@bjoernhaeuser I'm assuming you're using `ext.grid` found either in the wiki or my personal dotfiles? In which case, there are "margin" variables you can set to 0.
