### ISSUE TITLE
return a sequence of keystrokes (enhancement)

### ISSUE THREAD

**Issue by bglnelissen** [sdegutis/mjolnir#204]
My idea is that Hydra returns a number of keystrokes when I press a key combination. Like 'cmd' 'alt' 'shift' '@' would enter my email adres. This is probably on the limit of what Hydra is created for.

**Comment by sdegutis** [comment]
Good idea! So good actually that it's been filed as another issue. I can't figure out which one though.

**Comment by sdegutis** [comment]
Yeah definitely #187, not sure if #9 is separate or not. Thanks @Habbie! Marking this as duplicate.
