### ISSUE TITLE
Is there a guide on how to start playing with hydra?

### ISSUE THREAD

**Issue by tiye** [sdegutis/mjolnir#208]
I downloaded the package in release page and it began to run. Well, I'm not sure if it is really running or not. The "Hydra" process can be found in Activities Monitor, but not in App Switcher. Also I cannot find it in the panel( I saw that the first time I installed it but not any more).
And I have went through the docs, Lua code looks quite familiar to me. But is there a guide for beginners?

**Comment by sdegutis** [comment]
@jiyinyiyong Good question. I tried to answer this in the [documentation overview page](http://sdegutis.github.io/hydra/). Can you read through it and tell me if it clarifies things? If it doesn't help any, then I would love to know how I can improve it to help new users get started. Thanks!

**Comment by sdegutis** [comment]
@jiyinyiyong That would only happen if your `init.lua` is just not showing the menu icon. Can you paste your exact `init.lua` in here as it looks when you experience this behavior?

**Comment by sdegutis** [comment]
@jiyinyiyong Yes.
@muescha Can't agree.
