### ISSUE TITLE
Better sample config process for first-time users

### ISSUE THREAD

**Issue by jsanders** [sdegutis/mjolnir#210]
This is just a little idea for an enhancement to the on-boarding process for first time users, so feel free to reject it.

The links to the sample config in the readme go to the github rendered view instead of the raw file, so when I did a simple right-click, copy-link-location, wget paste-link-location, I got a bunch of HTML instead of the lua file I wanted. It would be just a bit nicer if those links were to the raw file, and perhaps also if it were renamed init.lua so that it doesn't require a rename. I know there is already a copy-paste workflow in the default config to get the same result, but wget'ing the whole file seems like a better programmer's solution.

**Comment by sdegutis** [comment]
:+1:

**Comment by sdegutis** [comment]
One benefit of linking to the non-raw file was the syntax highlighting. Users could just click it, and browsing the sample init.lua would be easier than if it was all monochromatic (unless the user is Rob Pike). I still think that has value. We could just add a "raw code" link next to it that points to the raw version?

And yeah I see your point about renaming it to init.lua, but then it's not clear that it's just a sample. Doesn't `wget` take an option for the local filename? Then you can just add `init.lua` at the end.
