### ISSUE TITLE
when updating to new version, need to redo accessibility permissions

### ISSUE THREAD

**Issue by nealeyoung** [sdegutis/mjolnir#214]
I installed the latest version of hydra.  Hydra then stopped working in that it was apparently unable to get the focused window.  e.g. in

```
function movewindow_rightside()
  local win = window.focusedwindow()
  local newframe = win:screen():frame_without_dock_or_menu()
  newframe.w = newframe.w / 2
  newframe.x = newframe.w
  win:setframe(newframe)
end
```

win would have a nil value.  The /var/log/system.log showed the line

```
   Jul  9 13:49:35 .... tccd[171]: Unable to verify code signing identity of org.degutis.Hydra:  code failed to satisfy specified code requirement(s)
```

I was able to fix the problem by returning to system preferences, unchecking, and then rechecking the "accessibility" checkbox that gives hydra permission to control the computer:
![image](https://cloud.githubusercontent.com/assets/965060/3531073/8c7a3418-07ab-11e4-9671-490bde23d1d5.png)

**Comment by sdegutis** [comment]
:+1: this is super annoying

**Comment by sdegutis** [comment]
Closing as dup of #209.
