### ISSUE TITLE
Sluggish on application:activate() (about 150ms delay)

### ISSUE THREAD

**Issue by alederer** [sdegutis/mjolnir#215]
This delay of around 150 milliseconds occurs when calling `application:activate()` via hotkey or REPL, and regardless of what application (tested with iTerm2, Chrome, Firefox).

`application:hide()` on the other hand has no noticeable delay.  I also noted the same application activation delay behavior in Phoenix, but no delay in Slate.  Operating on new Mac under low load.

**Comment by sdegutis** [comment]
@alederer Thanks for the report. Will investigate.

**Comment by sdegutis** [comment]
@alederer You said it's faster in Slate, but I don't see such a method in Slate's API: https://github.com/jigish/slate/wiki/Application-Object -- what method are you using to activate an app in Slate?

**Comment by sdegutis** [comment]
@fent Thanks.

**Comment by sdegutis** [comment]
@alederer Just pushed new code that focuses an app the same way Slate does; I experienced no delay with either the old code or this new code; can you build from master, test it, and verify that the delay is gone? Thanks.

**Comment by sdegutis** [comment]
I'm really at a loss here. Just tested it on master, using the following code, which you can copy and `pbpaste | hydra` while master is running (assuming you've done `ipc.link()`).

``` lua
apps = application.runningapplications()
app = fnutils.find(apps, function(app) return app:title() == "Xcode" end)
hydra.alert(app:title())
-- app:hide() -- throw this in too for good measure
app:activate()
```

**Comment by sdegutis** [comment]
@alederer I observed the same behavior.

**Comment by sdegutis** [comment]
@alederer By taking out the `allwindows` boolean option, I've made it faster, but still not instant. The example you've given will hide Xcode and bring me back to the Terminal (which is thus not hidden). But when I remove the `sleep` line, I still see that the Terminal is hidden instead, indicating that it's not instant.

**Comment by sdegutis** [comment]
For the record, this change is in b7c37716bbbfd7bda20e082c9cc733a12e2e7ac9 (I forgot to reference this issue in the commit message).

**Comment by sdegutis** [comment]
@alederer I've released Hydra 0.13 which has the faster `application:activate()` method. It may be the best we can do, seeing as it's the same method Slate uses to activate its applications. But it also may be fast enough for your purposes.

**Comment by sdegutis** [comment]
Hmm. Will continue to look into what Slate does. Can you provide a very simple Slate config (hopefully 1 or 2 lines) that demonstrates the exact behavior but is faster than Hydra?

**Comment by sdegutis** [comment]
Thanks.

**Comment by sdegutis** [comment]
@alederer 

Just looked through Slate's source code for [focus](https://github.com/jigish/slate/blob/master/Slate/AccessibilityWrapper.m#L165) and [hide/show](https://github.com/jigish/slate/blob/master/Slate/VisibilityOperation.m#L57-L69), and there was indeed a difference in our implementations. For some reason I was doing it through the slower API. I just pushed 1d3a497 which changes to using the faster API. That should work.

As a test-case, I translated that Slate config to the following Hydra code:

``` lua
hotkey.bind({"alt"}, "x", function()
    local app = fnutils.find(application.runningapplications(), function(app) return app:title() == 'Xcode' end)
    if app == window.focusedwindow():application() then
        app:hide()
    else
        app:unhide()
        app:activate()
    end
end)
```

**Comment by sdegutis** [comment]
@alederer Ah yes I see now, Slate has some optimizations. I'll see if I can emulate them.

**Comment by sdegutis** [comment]
@alederer I've pushed 3935b99 that should improve the speed of `app:activate()`

**Comment by sdegutis** [comment]
@alederer I understand a little better now, thank you. I did notice an extremely small difference in the delays when using Slate compared to Hydra. But having looked through the source code for the focus operation in Slate, I can't see any difference at all between the way Slate focuses an app and the way we do in `app:activate()`. So I'm really at a loss here.

**Comment by sdegutis** [comment]
Ah, I see now what that code does; here would be the Hydra equivalent:

``` lua
local win = app:focusedwindow() -- we don't have this
if win then
  win:becomemain()
  app:bringtofront() -- we don't have this either
else
  app:activate()
end
```

Looking at the implementation of `app:bringtofront()` it is indeed more efficient, but for a while I was very confused as to why `app:activate()` was implemented using a different, slower API. But now I understand: `app:activate()` does more than just bring the app to the front, it ensures that it has a key window; if we already have one, we can bypass that entirely and simply make it main ourselves.

**Comment by sdegutis** [comment]
@alederer The latest commit (cbd1f7b) uses this same code, thus `app:activate()` should indeed be faster now for the general case.

**Comment by sdegutis** [comment]
Actually this is the commit, sorry: c0b50d9

**Comment by sdegutis** [comment]
:cake:

**Comment by sdegutis** [comment]
Awesome. Now all that's left before we can release 1.0 is issue #1. Exciting!

**Comment by sdegutis** [comment]
@alederer I am skeptical that changing that code around is what actually improved the speed for you. All it's doing is guaranteeing that `self:_bringtofront(...)` is called regardless of the success of `win:becomemain()`. The order and timing should be identical.

**Comment by sdegutis** [comment]
@alederer Can you try it in ad04c15 and see if this delay still happens for you?

**Comment by sdegutis** [comment]
@alederer Not having any expertise in the accessibility APIs myself, I can't say with any authority why this is happening and if it's inevitable. But I have only seen 2 APIs to hide and unhide a window (AXUIElement functions and NSRunningApplication methods). Unless there is something else I'm missing, we've tried everything. I'm not sure that adding an intentional delay into Hydra is the best thing to do.

**Comment by sdegutis** [comment]
@alederer You're right, it's an inherently race-prone situation; KVO is ugly and we're probably going to use AXObservers for this instead.
