### ISSUE TITLE
Listen for distributed notifications

### ISSUE THREAD

**Issue by pbdeuchler** [sdegutis/mjolnir#217]
Be able to create alerts and trigger window events based on iTunes events (song changes, mostly)

**Comment by sdegutis** [comment]
Pretty simple...

``` objc
[[NSDistributedNotificationCenter defaultCenter] addObserver:self selector:@selector(gotEvent:) name:nil object:nil];
```

Not sure what the API should look like. I'm almost certain that call should be opt-in, since it's probably inefficient and not everyone will want it.

**Comment by sdegutis** [comment]
We'll translate the `userInfo` into a Lua table just like we do in the `json` and `settings` modules, and give it to you in Lua to handle.

**Comment by sdegutis** [comment]
Whoa! +1 @af <3

**Comment by sdegutis** [comment]
I should totally add some CFMessagePort stuff to [Bahamut](https://github.com/sdegutis/bahamut) so I can do the same thing in my Hydra configs!

**Comment by sdegutis** [comment]
@benfb Please add to the wiki! :)

**Comment by sdegutis** [comment]
Nah that's fine.

**Comment by sdegutis** [comment]
Not sure what this should be named. I wanted to go with `notify.listen` but there's already `notify.register` and `notify.unregister`. The `notify` module is related to this but not quite the same thing. Plus whatever the `listen` function returns has to have a method for "unlistening".

**Comment by sdegutis** [comment]
It's not fully featured yet, but it should be good enough for this use-case. In the future, I want to add the ability to listen only for notifications with a given name and/or object. Also it should be trivial to add a function to send distributed notifications too.
