### ISSUE TITLE
Opening the Hydra button in the menu bar does not work using only the keyboard

### ISSUE THREAD

**Issue by ghost** [sdegutis/mjolnir#220]
^F8 highlights the menu bar, but it is not possible to open the Hydra menulet it displays using the keyboard only. Some third party apps have this functionality, but I'm no OS X hacker, so I do not know what is needed to achieve it.

**Comment by sdegutis** [comment]
@endrebak What apps have this functionality?

**Comment by sdegutis** [comment]
@endrebak There is no public API to do this.
