### ISSUE TITLE
Some windows can't be moved to overlap the menu bar.

### ISSUE THREAD

**Issue by bglnelissen** [sdegutis/mjolnir#224]
Some windows can move their titlebar above the OSX menu bar, other programs cannot. The following example is using BBedit. The window is moved to the top, and the window title bar moves outside under the OSX menubar. This is expected behavior.

``` lua
local function QuakeTerminal()
    hydra.alert("QuakeTerminal")
    application.launchorfocus("BBedit")
    timer.doafter(0.1, function()
  local win = window.focusedwindow()
  -- local screen = win:screen():frame_including_dock_and_menu()
    local screen = win:screen():frame_without_dock_or_menu()
    win:setframe({x = screen.x+(screen.w/4), y = screen.y, w = screen.w/2, h = screen.h/4})
    end)
end
hotkey.bind(mash, "`", QuakeTerminal)
```

The following example is using Terminal. The window is moved to the top, and the window title bar moves until just under the OSX menubar. This is not what I expected.

``` lua
local function QuakeTerminal()
    hydra.alert("QuakeTerminal")
    application.launchorfocus("Terminal")
    timer.doafter(0.1, function()
  local win = window.focusedwindow()
  -- local screen = win:screen():frame_including_dock_and_menu()
    local screen = win:screen():frame_without_dock_or_menu()
    win:setframe({x = screen.x+(screen.w/4), y = screen.y, w = screen.w/2, h = screen.h/4})
    end)
end
hotkey.bind(mash, "`", QuakeTerminal)
```

Is this a feature or due to limitations of OS X? Or has it something to do with the use of GUI elements?

ps. and another issue perhaps, I have to set `timer.doafter(0.1, function()`, else the proper window is not found. this might be a bug... (or bad coding on my part ;)

**Comment by sdegutis** [comment]
@bglnelissen Typically windows can't be moved so that their titlebars overlap with the system menubar. If it can, that sounds more like a bug to me than anything else.
