### ISSUE TITLE
Suggestion: Add repl.open() to fallback menu

### ISSUE THREAD

**Issue by asmagill** [sdegutis/mjolnir#225]
A suggestion: add a way to open the console/log window from the fallback init's menu... I came back after a few days and found that my init file wasn't loading after an update... discovered you'd removed douserfile, but couldn't get (easily) in to check the docs for hydra to find out why... 

The good: I have perused the comments and issues and feel I know more now :-)
The bad: my default go-to was no where to be found :-(

Any way, thanks for a great project and I hope to contribute at some time when I know it better.

**Comment by sdegutis** [comment]
@asmagill Thanks!
