### ISSUE TITLE
application:activate() on stalled application stalls Hydra

### ISSUE THREAD

**Issue by alederer** [sdegutis/mjolnir#226]
This comes up when you have an application that is in a beach-ball state (easy to test by attaching a debugger to any application with Xcode and hitting pause).  Running application:activate() on that app will not return, causing Hydra to become stalled for a long period (from 5 to 30 seconds).

To reproduce, use Xcode to attach and pause e.g. Firefox and run the following in the REPL:

``` lua
apps = application.runningapplications()
app = fnutils.find(apps, function(a) return a:title() == "Firefox" end)
app:title() --returns Firefox, no problem
app:hide() --does nothing but returns no problem
app:unhide() --does nothing but returns no problem
app:activate() --Hydra is now beach-ball for quite a while
```

While there's no expectation that Hydra can focus an unresponsive app, ideally it could still be usable for actions on other apps rather than stalling.  A side-effect of Hydra stalling is that hotkey actions get queued, so when Hydra does return to responsive state, a bunch of queued actions may happen all at once.

**Comment by sdegutis** [comment]
@alederer Hmm good point. I'm pretty sure this can be fixed by a check within the app, and I think I know where to put it. For reference, are you seeing this behavior on master (which has the improved `app:activate()` code from issue #215?

**Comment by sdegutis** [comment]
@alederer Thank you for your continued excellence in providing detailed information to assist me in fixing these bugs.

**Comment by sdegutis** [comment]
:heart:

**Comment by sdegutis** [comment]
@alederer The commit fc9d5f5 should fix this. Seems to work for me. Can you verify?

**Comment by sdegutis** [comment]
@alederer That sounds like something outside of our control.
