### ISSUE TITLE
Custom Remapping of Hotkeys

### ISSUE THREAD

**Issue by muescha** [sdegutis/mjolnir#229]
as #192 i understand with the custom package management i can add some predefined packages to my own settings. for example window moving - i dont need to write my own - it is in an predefined package. and when updates comes to this package it is downloaded again

if i have the hotkeys (my own flavor) are changed, then with the update of a package this hotkeys are overwritten. thats why i suggested a hotkeys mapping

instead of 

`hotkey.new({"cmd", "ctrl", "alt"}, "L", movewindow_righthalf):enable()`

there should every package use a more generic way:

`hotkey.new(custom.MOVE_WINDOW_RIGHT_SHORTCUT, movewindow_righthalf):enable()`

and in a seperate file i can define something (pseudocode) if the windows moving package is declased with some namespace `ext.window.move`: 

`ext.window.move.MOVE_WINDOW_RIGHT_SHORTCUT={{"cmd", "ctrl", "alt"}, "L"}`

now an update of the window moving package dont change my shortcuts

PS:
and a REPL script should go through the packages and list all usages of this hotkey mappings and display it (also with already defined keys) so i can use this output (copy from repl or pipe it to a file) to create/update my my hotkey settings file add non assigned keys to it.

**Comment by sdegutis** [comment]
@muescha The cleaner way is for `ext` packages to somehow "publish" their public methods, and you just bind your own hotkeys to their functions, like I do in my own `init.lua` file: https://github.com/sdegutis/dotfiles/blob/osx/home/.hydra/init.lua#L43-L46
