### ISSUE TITLE
Add GUI hotkey editor

### ISSUE THREAD

**Issue by muescha** [sdegutis/mjolnir#230]
the idea of remapping for Hotkeys decribed in #229

a GUI should show all possible hotkeys my cutom settings file and i can change it in a GUI

why: if i create a custom hydra install package for my friends/others then they maybe not programmers and dont like to go to a settings file. they like to change the keys in a GUI

**Comment by sdegutis** [comment]
@muescha This is still a valid suggestion even without #229 (which was closed as invalid).
