### ISSUE TITLE
First repo.open shows icon, but not later ones

### ISSUE THREAD

**Issue by asmagill** [sdegutis/mjolnir#234]
If you open the repl textgrid, the first time the icon will show in the Dock.  If you close the window (click on the red x or Cmd-W), and then reopen the textgrid, the icon stays missing.

Minor, but an inconsistency.

**Comment by sdegutis** [comment]
@asmagill Good catch!

**Comment by sdegutis** [comment]
Fixed on `next` branch. Soon to be merged.
