### ISSUE TITLE
Don't hardcode install paths

### ISSUE THREAD

**Issue by g5pw** [sdegutis/mjolnir#236]
In the 0.13 release I noticed the install paths for the new hydra CLI and its man page are hardcoded. It would be really great if a environment variable would be provided to specify a custom install path for the binary and the man page (e.g. in MacPorts, we have all our stuff in /opt/local).

**Comment by sdegutis** [comment]
@g5pw Look at `doc.ipc.link`, it mentions an optional prefix for this.
