### ISSUE TITLE
Frame issues with multiple displays

### ISSUE THREAD

**Issue by keith** [sdegutis/mjolnir#239]
I have a center function that looks like this:

``` lua
function ext.grid.center()
  local win = window.focusedwindow()

  local winframe = win:frame()
  local screenframe = ext.grid.screenframe(win)
  local newframe = {
    x = screenframe.w / 2 - winframe.w / 2,
    y = screenframe.h / 2 - winframe.h / 2,
    w = winframe.w,
    h = winframe.h,
  }

  win:setframe(newframe)
end
```

Note that this `grid` is not the grid from @sdegutis's config.

This works fine on the main screen, where it centers the window in the screen. But when the focused window is on a second screen it puts it in the top left quadrent of the first screen. This seems to be because calling `window.focusedwindow():frame().x` on a second screen does not return 0, it returns the width of the first screen, plus the width of the second.

Suggestions?

**Comment by sdegutis** [comment]
@Keithbsmiley Is the issue fixed by using `screen:frame_including_dock_and_menu()`?

**Comment by sdegutis** [comment]
Assigned to @Habbie, he's super smart.

**Comment by sdegutis** [comment]
@Keithbsmiley Try this code, I think it should center it on the screen it's currently on.

``` lua
local win = window.focusedwindow()
local screenrect = win:screen():frame_including_dock_and_menu()
local f = win:frame()
f.x = screenrect.x + ((screenrect.w / 2) - (f.w / 2))
f.y = screenrect.y + ((screenrect.h / 2) - (f.h / 2))
win:setframe(f)
```

**Comment by sdegutis** [comment]
@Keithbsmiley :+1:

**Comment by sdegutis** [comment]
@muescha The last algorithm I posted in here seems trivial enough by itself without needing to be packaged up.
