### ISSUE TITLE
Display Lua errors in full instead of abbreviating them in a notification

### ISSUE THREAD

**Issue by reasonableperson** [sdegutis/mjolnir#253]
Config development would be easier if the full output from Lua was visible.

![hydra-notification-screenshot](https://cloud.githubusercontent.com/assets/1313976/3608499/46af2626-0d61-11e4-8267-a3f6aef96a0f.png)

**Comment by sdegutis** [comment]
Agreed, this notify.show stuff isn't ideal for errors.

**Comment by sdegutis** [comment]
My proposed solution for this is to open the log window when there's an error, which already shows errors. But the log window will need to be fixed to stop truncating lines.

**Comment by sdegutis** [comment]
The errors are also shown in Console.app, which should let you see the full message.
