### ISSUE TITLE
add sub menus to hydra menu?

### ISSUE THREAD

**Issue by asmagill** [sdegutis/mjolnir#255]
Is it possible to create herarchical menus within the hydra menu?  It's not a big deal, but it might be useful to extend menu functionality to add submenus or enable/check/disable a menu item.

**Comment by sdegutis** [comment]
@asmagill What's the use-case for this?

**Comment by sdegutis** [comment]
Right now menu items can be disabled and checked by adding a key to it, I forgot what key (the source code can tell you that). As for submenus, that seems a bit overcomplicated and I can't think of a good reason someone would want that.

**Comment by sdegutis** [comment]
@asmagill I'm still not convinced submenus should even be in the code.

**Comment by sdegutis** [comment]
Honesty if I change anything about the menu module, it's probably going to be a lot different, and probably you'll have instances of menus and menu items...
