### ISSUE TITLE
Battery API

### ISSUE THREAD

**Issue by jhgg** [sdegutis/mjolnir#261]
Would anyone be interested in this? 

A battery module to query for the status of the battery? if it's charged, how long's left, etc?

**Comment by sdegutis** [comment]
I would.

**Comment by sdegutis** [comment]
:cactus:

**Comment by sdegutis** [comment]
I'd love to have some kind of event handler for when battery status and energy levels change, so that I can have it pop up at 30% and show an alert that's like "hey, plug your laptop in soon dude"

**Comment by sdegutis** [comment]
:+1:

**Comment by sdegutis** [comment]
But let's hold off on that until #241 is done.

**Comment by sdegutis** [comment]
@jhgg Finished #241, so go for it. Look at timer.m for an example of the pattern for event handlers; also we need to add any new stopall or disableall functions to `clear_old_state`.

**Comment by sdegutis** [comment]
@jhgg Also, don't do #116 I want to try my hand at it :P
