### ISSUE TITLE
w:otherwindows_samescreen() populated with phantom windows

### ISSUE THREAD

**Issue by bcarrell** [sdegutis/mjolnir#263]
With two windows on a screen (one focused), I expect the total windows on the screen from  `window:otherwindows_samescreen()` to be 1 (+ 1).

Instead, I get something like 4 or sometimes 5 with multiple of those windows being pretty much non-existent.

So I wrote something like this to get rid of these phantom windows, since I really only want to operate on the windows that I can see.

```
ws = fnutils.filter(ws, function(win)
  return win:isvisible()
end)
```

Which didn't work (also tried `isstandard`) -- phantom windows remained, so then I realized that these windows had blank titles too, so I changed the above function to:

```
ws = fnutils.filter(ws, function(win)
  local title = win:title()
  return win:isvisible() and string.len(title) > 0
end)
```

Which totally works great and got rid of them, but I'm still kinda wondering why `window:otherwindows_samescreen()` is populated with numerous other windows that don't exist, since there could be a case where I have a legit window without a title.  

I'm only running Chrome and terminal.  Thought it might have been Alfred or something, but no go on that.

Any ideas?

**Comment by sdegutis** [comment]
Assigned to 1.0 milestone to investigate.

**Comment by sdegutis** [comment]
@bcarrell What does `win:application():title()` return for these phantom windows?

**Comment by sdegutis** [comment]
@bcarrell By the way, if there was any ambiguity on the app title, you could verify with `application():bundleid()`. But it sounds like you've already verified it another way.

**Comment by sdegutis** [comment]
@bcarrell Anyway, this is indeed strange. Not sure how it's doing that.

**Comment by sdegutis** [comment]
@bcarrell Thanks :)

**Comment by sdegutis** [comment]
@jhgg At least it's a known issue. Maybe we should include a helper function like `window:hastitle()`, so that we don't have to hardcode title-less windows into any core functions (other apps may use them, and the user may not always want them filtered out if they're an otherwise-normal window).

**Comment by sdegutis** [comment]
Or, since `window:title():len() == 0` already works and is mostly the same, we could just make reference to this odd fact in the documentation, and let the user sort it out themselves as-needed.

**Comment by sdegutis** [comment]
@jhgg let's wait until it becomes a problem and open an issue if that happens

**Comment by sdegutis** [comment]
@bcarrell Perhaps `win:isvisible()` should be named better; it currently returns true if (1) the app it belongs to isn't hidden (e.g. via Cmd-H) and (2) the window isn't minimized. It doesn't actually need to be visible for this to return true, hence it's probably misnamed. But I don't have a better name.

**Comment by sdegutis** [comment]
@bcarrell I'm skeptical that it's the menu bar icon that's showing up in your list of windows.. it's more likely an offscreen window or something.. you can print its position to verify this.

**Comment by sdegutis** [comment]
That is totally cheating, Adobe. Totally cheating.

**Comment by sdegutis** [comment]
@bcarrell Just for my own curiosity, can you move it on-screen programmatically (using Hydra) and see what it looks like? And if so, is it a familiar window?

**Comment by sdegutis** [comment]
Ha! Sounds like Adobe has an invisible NSWindow using NSBorderlessWindowMask and drawing nothing. How clever. Oh well, the best we can do is make special-cases in our own configs for this kind of software.
