### ISSUE TITLE
API to control keyboard backlight...

### ISSUE THREAD

**Issue by jhgg** [sdegutis/mjolnir#268]
I think this would be pretty neat. 

And completely possible, just have to use some private APIs... to manipulate `AppleLMUController`. But with a bit of code, you can make the keyboard backlight turn on and off, and set the brightness level of it just like the display. 

Would anyone be interested in this? 

Some resources: 
- http://read.pudn.com/downloads147/sourcecode/windows/637028/IO_Script/stevedekorte-io-6727dd4870686b3d75af6dc98bc0ec386b41fde1/addons/AppleExtras/source/AppleSensors.c__.htm
- http://arstechnica.com/civis/viewtopic.php?f=19&t=280204&start=40
- http://www.osxbook.com/book/bonus/chapter10/light/

And the ambient light sensor... is accessible too... if you're so inclined to get that.

**Comment by sdegutis** [comment]
@jhgg Perfect.
