### ISSUE TITLE
"Attempt to call upvalue" error. 

### ISSUE THREAD

**Issue by ghost** [sdegutis/mjolnir#282]
Upon download, move to Applications folder, and initial launch of Hydra, this Mac OS X notification appeared: 
<a href="http://imgur.com/ofaLkgI"><img src="http://i.imgur.com/ofaLkgI.png" title="Hosted by imgur.com" /></a>
"Hydra Error – /Applications/Hydra.app/Contents/Resources/updates.lua:11:attempt to call upvalue 'fn' (a n…"

Clicking the notification caused it to disappear. The app launched and initially seems to run. Any ideas what this meant? Thanks! 

Hydra Version 0.13 (0.13)
Mac OS X 9.4 Mavericks

**Comment by sdegutis** [comment]
@janaspage No idea :)

**Comment by sdegutis** [comment]
@jhgg Cmd-Shift-4, then space to capture only a window, then click a window.

**Comment by sdegutis** [comment]
@janaspage What version of Hydra are you using?

**Comment by sdegutis** [comment]
Oops, yeah I see that now, at the bottom. Sorry.

**Comment by sdegutis** [comment]
@janaspage You most likely found the only bug left in 0.13, congratulations! :confetti_ball:

**Comment by sdegutis** [comment]
@janaspage What configs were you using when this happened, if any?
