### ISSUE TITLE
`spaces.movetospace()` shows blank screen with displays have separate spaces enabled

### ISSUE THREAD

**Issue by fent** [sdegutis/mjolnir#297]
I'm on OSX 10.9.4 and I'm guessing this happens because I have "Displays have separate Spaces" enabled in Mission Control preferences.

I usually have just one space on my external monitor and multiple on the main one. I'm guessing it tries to switch to the a space on both monitors, it can't on the external monitor and it shows a blank screen.

Using the gesture on the touchpad/mouse shows the space correctly again.

**Comment by phoenixanimations** [comment]
Hi I've never really tinkered with this kind of stuff (I love slate though), and I was wondering how would I go about disabling the animation when switching between spaces? I see the code obviously but have no idea where to go to modify the bool. 

Thanks for helping, and this is some amazing stuff (reverse engineering a undocumented program on software that really doesn't want you to touch it).
