### ISSUE TITLE
Use github-release to upload new builds

### ISSUE THREAD

**Issue by colindean** [sdegutis/mjolnir#46]
Rather than checking them into the repo, perhaps use Github's Builds hosting.

There's a program called [github-release](https://github.com/aktau/github-release) that handles this. It even dogfoods itself, [releasing using itself](https://github.com/aktau/github-release/releases/tag/v0.5).

**Comment by sdegutis** [comment]
Whoa that sounds awesome!

**Comment by sdegutis** [comment]
Yeah totally, I'm looking around on this repo's settings to try and find out how to use the releases feature.

**Comment by sdegutis** [comment]
Whoa, [this sounds so cool](https://github.com/blog/1547-release-your-software). (Yeah I know, welcome to mid-2013 @sdegutis.)

**Comment by sdegutis** [comment]
This totally lets us get rid of the ugly/hacky `Builds/` dir and `version.txt` and `CHANGES.txt` files. So cool!

Although I don't see file-signatures as a first class attribute (version.txt currently contains this, i.e. `MC0CFBBHr86WoEvkyEyCSm8JNh1gakwCAhUAvebbbYiq+lIU8siqFt2hGGkzXPk=`). But we can stick it nonchalantly at the bottom of the changelog body, and just assume this convention in the auto-update API.

**Comment by sdegutis** [comment]
Fwiw I'm considering stripping the git history of the Build folder (and probably deleting the entire tree from its Hydra's Phoenix history) to clean this up a bit since we won't have builds in here anymore.

**Comment by sdegutis** [comment]
As it is, the process is quite trivial right now and I'm okay with it currently, so long as we don't begin to need to release a new version every few hours. But more importantly, avoiding github-release is a perfect opportunity to boycott Go.
