### ISSUE TITLE
Please add Macports support

### ISSUE THREAD

**Issue by ztomer** [sdegutis/mjolnir#461]
Macports installs lua to /opt/local/bin vs homebrew's /local/bin
Luarocks installs to (for example):
/opt/local/share/luarocks/share/lua/5.2/mjolnir/hotkey.lua
/opt/local/share/luarocks/lib/lua/5.2/mjolnir/hotkey/internal.so

Mjolnir seems to be hardcoded to search in /usr/local/
Extensions are expected to be installed to (for example):
'/usr/local/share/lua/5.2/mjolnir/application.lua'
'/usr/local/lib/lua/5.2/mjolnir/application.so'

Can you please check Macports install path as well?

**Comment by asahui** [comment]
@ztomer You should read the FAQ and the error log carefully.
Can't you see that 'mjolnir/mjolnir' in your error log? It means that lua find the module with its own name which is the directory itself. SO below works..

package.path = package.path .. ';/opt/local/share/luarocks/share/lua/5.2/?.lua'
package.cpath = package.cpath .. ';/opt/local/share/luarocks/lib/lua/5.2/?.so'
