### ISSUE TITLE
Package as .dmg instead of .tar.gz

### ISSUE THREAD

**Issue by colindean** [sdegutis/mjolnir#47]
More idiomatic for OSX users, IMO.

**Comment by sdegutis** [comment]
Hmm, interesting proposition. May I present to you my counterargument, good sir: I hate .dmg files so bad, way bad indeed.

**Comment by sdegutis** [comment]
Personally I prefer to get a .zip file, that way I can just double-click it and The Unarchiver (who doesn't own this awesome, free app?) just unzips it in-place and I don't have to worry about "ejecting" any mounting .dmg files and stuff. Also I often accidentally launch the app from inside the .dmg which led rise to the recently ubiquitous popup "hey this isn't in /Apps, want me to put it there?" dialog.

**Comment by sdegutis** [comment]
Meh they're actually not that bad to create, mostly just for me (the end-user) to use. In fact actually it's easy enough that we could probably just create both a .zip and .dmg and upload them both to the github release and let the user decide what format to use (assuming the github releases feature allows this).

**Comment by sdegutis** [comment]
Yeah I run them there until I decide I like them, in which case I move them to Dropbox/Apps, or delete them if it sucks.

**Comment by sdegutis** [comment]
Okay. Exploring the possibilities with this new API. Testing it out. If it's not way too painful, I'll include both.

**Comment by sdegutis** [comment]
Okay, closing this in that case.

**Comment by sdegutis** [comment]
Also,

> I’ve always been a fan of including a symlink to /Applications in the dmg.

I never use those symlinks, because for many years I put my apps in ~/Applications, and recently I started putting them in ~/Dropbox/Applications (may switch back to the former).

(Actually, once I did, because the symlink went to ~/Applications instead I think. But that's so rare and problematic in itself.)
