### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by keith** [sdegutis/mjolnir#48]
Is there a reason for the config file path to be `~/.hydra/init.lua` instead of just `~/.hydra.lua`?

**Comment by sdegutis** [comment]
1. Figured users would want to extract their ancillary functionality into modules (like my future `grid.lua`)
2. Figured people would want to distribute libraries you could just drop right into `~/.hydra` and instantly load up (hence `api.ext` which I should add to the documentation system [oops])

**Comment by sdegutis** [comment]
Yeah, emacs does that too. Not a bad idea. But making your own `~/.hydra` dir encourages really making your config your own and also encourages using third party libs. That plus simplicity makes me think we should just stick to the dir.
