### ISSUE TITLE
Breaks my Karabiner key bindings

### ISSUE THREAD

**Issue by chris838** [sdegutis/mjolnir#549]
Perhaps unsurprisingly, I can't get Mjolnir to work nicely with Karabiner. I use Karabiner to provide system-wide readline-like text manipulation and navigation shortcut keys.

It would be nice if I could just add these from Mjolnir instead, but I can't figure out how to execute commands like "move word forwards" or "delete word backwards".

**Comment by sdegutis** [comment]
@chris838 I don't know what Karabiner is. But OS X already comes with many readline key-bindings in nearly every (native) text field and text box. Plus, you can add even more via [DefaultKeyBinding.dict](http://www.google.com/search?q=DefaultKeyBinding.dict).

**Comment by chris838** [comment]
DefaultKeyBinding.dict actually has most of what I need - thank you!
