### ISSUE TITLE
Menu Icon is gone

### ISSUE THREAD

**Issue by mhartington** [sdegutis/mjolnir#557]
Not sure how this happened (probably my fault), but my menu icon for mjolnir has disappeared.
Is there a way from the command line to bring up the preferences? 
I've uninstalled mjolnir completely but it doesn't seem to fix things.
Any ideas?

**Comment by asmagill** [comment]
I'm assuming you also don't have the application icon showing in the Dock at the bottom?

It's been a while, but I think if you hit `CMD ,` (Command and Comma) immediately after starting up  Mjolnir, even with both the icon and the menu hidden, it will open up the preferences, but it has to happen before you've done anything else in any other application or focus will go to the other application.

If you do have the icon in the Dock, then click on it and either try the Command-comma or select Preferences in from the Mjolnir menu (left corner)

You could also try the following from the command line in Terminal:

~~~
defaults write org.degutis.Mjolnir MJShowMenuIconKey -bool TRUE
~~~

and then restart Mjolnir.

Hope one of these helps!

**Comment by mhartington** [comment]
YES! Forgot about the preferences shortcut. Thanks a lot, works like charm.
