### ISSUE TITLE
UTF-8 weirdness with os.execute

### ISSUE THREAD

**Issue by javjar** [sdegutis/mjolnir#559]
For some reason this doesn't work as expected:  
```lua
local function copyToClipboard()
  os.execute("echo ' áéíóú ' | tr -d '\n' | pbcopy")
end
hotkey.bind(mash, 'space', function() copyToClipboard() end)
```

You would expect this to get ` áéíóú ` in your clipboard, but what you really get is: ` √°√©√≠√≥√∫ `.
If I just open the stand-alone Lua interpreter and do: 
```lua
os.execute("echo ' áéíóú ' | tr -d '\n' | pbcopy")
```

I can paste: ` áéíóú ` as expected.

**Comment by javjar** [comment]
note that doing:  
```lua
alert.show("echo ' áéíóú ' | tr -d '\n' | pbcopy")
```
or
```lua
print("echo ' áéíóú ' | tr -d '\n' | pbcopy")
```

shows/prints everything as expected, for some reason this only happens with `os.execute` or `io.popen`

**Comment by sdegutis** [comment]
Oh good point. Hmm, I wonder if Mjolnir is passing input to Lua via ASCII instead of UTF-8.

**Comment by sdegutis** [comment]
To be honest I forgot how Mjolnir works anymore. I'll have to look into it. But most people seem to be using Hammerspoon these days anyway.

**Comment by javjar** [comment]
Ahm, interesting, gonna check Hammerspoon and see what's the behavior.

**Comment by sdegutis** [comment]
Just looked at the Lua-ObjC bridge code again. At all entry points, it seems to consume the code as UTF-8 and when it spits strings out, it does so as UTF-8. So I'm baffled.

**Comment by asmagill** [comment]
I'm curious what happens if you make the copyToClipboard function the keyUp rather than the keyDown function (insert a nil argument before the function in the keybinding)... it wouldn't be the first time we've seen weird behavior in both Mjolnir and Hammerspoon when keyboard modifiers were in the down state.  If you get a chance, let us know if that makes a difference -- I'll try it out in Hammerspoon later this evening when I get a chance as well.

**Comment by javjar** [comment]
Tried that, without different results. ;(

**Comment by cmsj** [comment]
While not addressing the underlying UTF-8 issue, I'd note that Hammerspoon has an hs.pasteboard which lets you get/set the clipboard directly. It should port across to Mjolnir without a huge amount of effort :)

**Comment by sdegutis** [comment]
Sure or you could just use Hammerspoon, it already has t.

**Comment by javjar** [comment]
I'm closing this and migrating to Hammerspoon then. <3
