### ISSUE TITLE
10.11.4 reset privacy settings

### ISSUE THREAD

**Issue by natewalck** [sdegutis/mjolnir#564]
Just updated to 10.11.4 and it unchecked the accessibility access for Mjolnir.app in System Preferences. This causde Mjolnir to only work on its own windows. Re-checking the box fixes it.

**Comment by sdegutis** [comment]
This is mentioned at the very top of the `Changes` section on the readme. Should it maybe be in the FAQ too?

**Comment by crodjer** [comment]
@natewalck Thanks for posting this!

**Comment by iveney** [comment]
Worked like a breeze :)
