### ISSUE TITLE
Unable to start on latest OSX 10.11.5

### ISSUE THREAD

**Issue by noroot** [sdegutis/mjolnir#565]
```
Welcome to the Mjolnir Console!
You can run any Lua code in here.

-- Loading ~/.mjolnir/init.lua
-- Done.
/usr/local/share/lua/5.2/mjolnir/sd/grid.lua:117: attempt to index local 'win' (a nil value)
stack traceback:
    /usr/local/share/lua/5.2/mjolnir/sd/grid.lua:117: in function </usr/local/share/lua/5.2/mjolnir/sd/grid.lua:114>
    [C]: in function 'xpcall'
    /usr/local/share/lua/5.2/mjolnir/hotkey.lua:23: in function </usr/local/share/lua/5.2/mjolnir/hotkey.lua:21>

```

**Comment by sdegutis** [comment]
@noroot It looks like your script is referencing a variable `win` that's no longer valid. What does your init script look like?

**Comment by noroot** [comment]
@sdegutis here it is https://gist.github.com/noroot/eb96563a588efeb9e3c0c430b918d89f thanks

**Comment by noroot** [comment]
@sdegutis any thoughts ?

**Comment by nloveladyallen** [comment]
Having the same issue. Here's the relevant line:

```lua
local f = window.focusedwindow():frame()
```

Obviously the issue is that `focusedwindow` is returning `nil`. The method is defined [here](https://github.com/sdegutis/mjolnir/blob/master/mods/application/window.m#L60).

**Comment by nloveladyallen** [comment]
Interesting that it seems to be working in Hammerspoon, even though its `focusedwindow` method is [identical](https://github.com/Hammerspoon/hammerspoon/blob/master/extensions/window/internal.m#L97) to Mjolnir's.

**Comment by jfarkas112** [comment]
I had the same problem after updated to 10.11. You need to give Mjolnir access to the accessibility features in system preferences -> security -> accessibility. 

The focusedwindow method uses an accessibility hook to get a reference to the window, without permission it returns nil.

**Comment by sdegutis** [comment]
Good eye, @jfarkas112. Case closed.
