### ISSUE TITLE
Resetting preferences to default

### ISSUE THREAD

**Issue by wengzilla** [sdegutis/mjolnir#567]
I recently unchecked the "pin from taskbar" before clicking "pin to menu bar" and now I have no way to get back to the preference panel! Is there a command I can run or a file I can modify to reset to the defaults (or alternatively just check the pin to menu bar)?

**Comment by sdegutis** [comment]
@wengzilla In a terminal, type `open -a Mjolnir`. That may open the Preferences panel of Mjolnir. If not, quit Mjolnir (via `kill`) and delete its Preferences plist file, then reopen it.

**Comment by AaronFoltz** [comment]
@sdegutis Any more suggestions here?  The deletion of the preferences plist doesn't seem to do anything.

**Comment by sdegutis** [comment]
Make sure to kill the process first then while it's not running use the defaults command to delete its preferences. Restart the app and it should be fine.
