### ISSUE TITLE
Multiple Accessibility popups

### ISSUE THREAD

**Issue by keith** [sdegutis/mjolnir#63]
I had the prebuilt v1.0b1 installed. Then I built the HEAD version and I got a second popup asking to enable accessibility access. There is no new entry in that pane for Hydra so I'm assuming there's something weird here.

**Comment by sdegutis** [comment]
Every time I release a new build (either via Xcode's Archive feature or `./release.sh`) and run the new binary, it says I need to enable accessibility. I agree, it's a huge pain. Not sure what can be done about it.

**Comment by sdegutis** [comment]
Indeed, which is what's causing the popup to happen: https://github.com/sdegutis/hydra/blob/master/Hydra/rawinit.lua#L27
