### ISSUE TITLE
Don't check for updates on reload

### ISSUE THREAD

**Issue by keith** [sdegutis/mjolnir#64]
The default config checks for updates on each reload. This seems like overkill with also having the menu item and registering the time which I assume persists across launches?

**Comment by sdegutis** [comment]
The timer checks for updates every 7 days, but does not fire initially. And as soon as the app quits, the timer does, so it starts over every time you launch. I couldn't think of a better way to make sure that it actually does check for updates if you end up quitting a lot for some reason. In retrospect, I guess anyone who ends up using the app long-term will probably never quit it, except maybe to move it to the right folder. But I would still like future first-time users to be able to see that there's an update in the event they got an old copy somewhere online down the road, before they spend a week investing in configs for an older API.

Maybe a good compromise is to have a one-off delayed-function that checks for updates 24 hours after launching, along with the periodic 7-day check.

**Comment by sdegutis** [comment]
Actually, that might be a good use-case for an API for user-defaults maybe? I was thinking earlier today of adding it in, but I couldn't think of a good reason. Then again, files are pretty easy to use too, and files can be made portable between machines (Dropbox, etc) whereas user-defaults can't. What do you think?
