### ISSUE TITLE
Support for key repeats

### ISSUE THREAD

**Issue by szymonkaliski** [sdegutis/mjolnir#69]
Any chances of key repeats coming to hydra? 
https://github.com/sdegutis/Phoenix/issues/14

**Comment by sdegutis** [comment]
Yep, will take a look.

**Comment by sdegutis** [comment]
A more flexible solution is to start your own `api.timer` (i.e. with a 0.25 second interval) when the key is pressed, and stop it when it's released. We will need either a way to check if it's still pressed, or a callback for when it's released.

**Comment by sdegutis** [comment]
We can make use of `kEventHotKeyReleased` for this.

**Comment by sdegutis** [comment]
This is now possible on the `next` branch:

``` lua
local timer = timer.new(0.1, function()
  -- do something here
end)
hotkey.bind(
  {"cmd"}, "d",
  function() timer:enable() end,
  function() timer:disable() end
)
```
