### ISSUE TITLE
move/resize windows by holding modifier keys + moving mouse

### ISSUE THREAD

**Issue by Habbie** [sdegutis/mjolnir#81]
I use hyperdock, with which i can do things like 'if i hold ctrl+option and move my mouse, the window below the pointer moves with it', and similarly, another combination will resize the window (by moving the lower right corner relative to my mouse movements). Would love to see the right hooks in Hydra to offer the same feature.

**Comment by sdegutis** [comment]
Most of this can already be done. You would use a new `timer` with a short interval (maybe 0.1), and `mouse.get()` to keep getting the location of the mouse. You'd save the initial position of the window and initial mouse point, so you can calculate the relative offset at each tick, and move the window relative from its initial position by the offset. The only thing we lack right now is the ability to see that a modifier was pressed and released by itself. That's different enough from global hotkeys that it could be a new API in itself.

**Comment by sdegutis** [comment]
Re-interpreting this issue as a question on what's needed to implement the feature described. My first response contains most of the answer; users will be able to efficiently implement this feature when both #82 and #83 are completed, without needing to poll via a timer.

**Comment by sdegutis** [comment]
@Habbie That can mostly be done by comparing coordinates. I could add `geometry.pointinrect(point, rect) -> bool` for convenience, but I'm sure this is something that could be done outside of the app in the meantime. The only other half of this is to get the "z-index" of overlapping windows. I'm sure it's possible, just don't know how; we should file an issue for that.

**Comment by sdegutis** [comment]
Yeah that's probably the only way. There may be another specialized function somewhere in the Accessibility API, but I'm not sure. I'll look. Anyway, I've created #88 which could be generally helpful anyway.
