### ISSUE TITLE
Listen to and override {mouse, keyboard, trackpad} events

### ISSUE THREAD

**Issue by sdegutis** [sdegutis/mjolnir#9]
I just found some code the other day that lets us capture every single key-event and override it.. not just handle it but literally switch it out. The sample code I found makes it so when you press "a" you really press "z", and vice versa. This would be an incredibly cool API to use. It could potentially also obsolete the existing hotkey API, but there may be side-effects or caveats I'm not aware of, so this should probably just be a new separate API for now.

I can't find the original site that I found it on, and the one original source that looks legit seems to be down now, but here's the code (I think):

``` objc
// alterkeys.c
// http://osxbook.com
//
// Complile using the following command line:
//     gcc -Wall -o alterkeys alterkeys.c -framework ApplicationServices
//
// You need superuser privileges to create the event tap, unless accessibility
// is enabled. To do so, select the "Enable access for assistive devices"
// checkbox in the Universal Access system preference pane.

#include <ApplicationServices/ApplicationServices.h>

// This callback will be invoked every time there is a keystroke.
//
CGEventRef
myCGEventCallback(CGEventTapProxy proxy, CGEventType type,
                  CGEventRef event, void *refcon)
{
    // Paranoid sanity check.
    if ((type != kCGEventKeyDown) && (type != kCGEventKeyUp))
        return event;

    // The incoming keycode.
    CGKeyCode keycode = (CGKeyCode)CGEventGetIntegerValueField(
                                                               event, kCGKeyboardEventKeycode);

    // Swap 'a' (keycode=0) and 'z' (keycode=6).
    if (keycode == (CGKeyCode)0)
        keycode = (CGKeyCode)6;
    else if (keycode == (CGKeyCode)6)
        keycode = (CGKeyCode)0;

    // Set the modified keycode field in the event.
    CGEventSetIntegerValueField(
                                event, kCGKeyboardEventKeycode, (int64_t)keycode);

    // We must return the event for it to be useful.
    return event;
}

int
main(void)
{
    CFMachPortRef      eventTap;
    CGEventMask        eventMask;
    CFRunLoopSourceRef runLoopSource;

    // Create an event tap. We are interested in key presses.
    eventMask = ((1 << kCGEventKeyDown) | (1 << kCGEventKeyUp));
    eventTap = CGEventTapCreate(kCGSessionEventTap, kCGHeadInsertEventTap, 0,
                                eventMask, myCGEventCallback, NULL);
    if (!eventTap) {
        fprintf(stderr, "failed to create event tap\n");
        exit(1);
    }

    // Create a run loop source.
    runLoopSource = CFMachPortCreateRunLoopSource(
                                                  kCFAllocatorDefault, eventTap, 0);

    // Add to the current run loop.
    CFRunLoopAddSource(CFRunLoopGetCurrent(), runLoopSource,
                       kCFRunLoopCommonModes);

    // Enable the event tap.
    CGEventTapEnable(eventTap, true);

    // Set it all running.
    CFRunLoopRun();

    // In a real program, one would have arranged for cleaning up.

    exit(0);
}
```

**Comment by sdegutis** [comment]
Maybe a potential name for this API could be `anykey`?

**Comment by sdegutis** [comment]
@cksachdev You probably can't, caps-lock is not a modifier key, just a regular key (c.f. `kVK_CapsLock`).

**Comment by sdegutis** [comment]
@cksachdev No idea, since I don't use PCKeyboardHack.

**Comment by sdegutis** [comment]
Just found out that we can indeed override keys such as caps lock, using even taps. At least I'm pretty sure.

**Comment by sdegutis** [comment]
Much of this is done on master in the `eventtap` module. Still need a better way to override events though.

**Comment by sdegutis** [comment]
@jhgg Expect a new release soon.

**Comment by sdegutis** [comment]
Note to self: add eventtap to some kind of registry and disable them all (implicitly clears them out) when the user reloads config.

**Comment by sdegutis** [comment]
First next thing to add: `eventtap.{get,set}keycode(event)`

**Comment by sdegutis** [comment]
Right now you can listen on all events. If you return nothing from the event handler, your event is returned as-is. If you return nil, the event is deleted as if it never happened.

**Comment by sdegutis** [comment]
I also want to support `CGEventTapPostEvent`. But in order to do this cleanly (i.e. without duplication), we should make it possible to create events from within Hydra, so we can share the same code within and outside of eventtap handlers. This will also simplify the `eventtap.postkey` function and other future similar functions.

But the main problem I'm having with this is naming the module. There's an `eventtap` and an `event` which are related but not the same thing. And in Hydra, you can have instances of both. But I don't want to create a separate `event` module since it's limited to input-related events, whereas we'll also have separate window/screen/app events. It's easy to imagine someone looking in the `events` lib for that functionality and getting confused only seeing input stuff.

The cleanest solution I can think of is nested modules, so that we'd have `eventtap` and `eventtap.event`. But our documentation system doesn't support nested modules. And honestly, it felt really good to rip that code out of our system.

The `audio` module has functions that produce `audiodevice` instances, and has methods for them. It documents them like `audio:name()` even though it's really `audiodevice:name()`. We could just go that route. But I think we should actually change that module to use something like this.

Maybe the best solution is to just allow modules to have a different instance-name in it in our doc generation system. I think that's the right way to go. Thus `audio` module could have `audiodevice:name()` and `eventtap` module could have `event:setflags()`.

**Comment by sdegutis** [comment]
Note: we'll have to make our `event` things use a metatable with __index on it.

Also, that solution isn't flexible, such that we won't be able to reuse the name `event` for window-related events or app-related events, etc.

Hmm.

**Comment by sdegutis** [comment]
I've settled on a solution for this one: use two different modules, `eventtap` and `inputevent`. They can refer to each other in the documentation.

But anyway, I'm reconsidering submodules.

**Comment by sdegutis** [comment]
Related: #254

**Comment by sdegutis** [comment]
Moving to 2.0 milestone, since #254 is quite enough to do before the icon and website are done.

**Comment by rileyjshaw** [comment]
@sdegutis thanks for adding this! The [docs that I've found](https://github.com/asmagill/mjolnir_asm.eventtap) have disappeared; can you add a simple example for how to listen to the caps lock key as suggested [here](https://github.com/sdegutis/mjolnir/issues/134)?

```
Caps Lock + left key -> moveLeft()
```
