### ISSUE TITLE
move sethasshadow

### ISSUE THREAD

**Issue by Habbie** [sdegutis/mjolnir#92]
Right now, sethasshadow is on webview. This means textgrid does not have it. We could move it to window, but that might be 'weird' if we can't actually do it on windows from other apps. Or we can just ignore that. Not sure how to proceed, but current situation is inconsistent.

**Comment by sdegutis** [comment]
A `webview` and `textgrid` do have a corresponding `window`, but not the other way around. We can only control such things (like whether a window has a shadow) for windows that belong to our app (i.e. Hydra). So moving these methods to `window` doesn't make sense.
