### ISSUE TITLE
About key sequence bind.

### ISSUE THREAD

**Issue by deftsp** [sdegutis/mjolnir#94]
I gave hydra a try. A very flexible one WM. Thanks.

But as a heavy Emacs user,  it's hard to find easy-press  mods key to hydra. Other WMs like stumpwm, XMonad ... , support key sequence. For example, after pressed  `CMD + i` , WM will wait for other key events, no need to press all of the keys at the same time.

I have read the docs, it seems to no way to bind keys like that for now. I think, to activate a window (may invisible one) to receive the follow-up key events is one way to implement that.

**Comment by sdegutis** [comment]
@deftsp ah this is a very good point indeed; I am also keen to have key-sequences, so I shall ponder about how they may be implemented

**Comment by sdegutis** [comment]
@deftsp one possible solution may be lurking in the form of issue #9; if we make that API flexible enough, you could enable the any-key API in some hotkey's callback function, get a callback for any kind of key pressed next, and disable the any-key API when you get one that takes you out of this "waiting for a key" mode. We could even call this new API `anykey`.

**Comment by sdegutis** [comment]
@deftsp Since this is a question, I'll mark it as closed (i.e. answered). The feature in issue #9 is what's needed to make this work. If you would like a more convenient wrapper around these features, please file another issue requesting it. Thanks :)
